### PR TITLE
Added simple quick start notebook

### PR DESCRIPTION
**Pull request by thecch**

### CODE REVIEW

**Comment by RyanSaxe** [comment]
Three things before I can merge:

1. Can you confirm that the path, regardless of whomever uses this on collab, will always start with "content" like that"? If not, please update to have a procedurally generated path depending on where this collab is run.
2. Move this notebook into the scripts folder, as it's just a way of calling those scripts in collab instead of the command line. 
3. Clear the output of the notebook

**Comment by thecch** [comment]
1. Path integrity is ensured within the code.
2. Done.
3. Done

**Comment by RyanSaxe** [comment]
Thank you. One last thing: I just refactored the codebase, which ended up changing a bit in terms of the API and training scripts (e.g. output_MLP is no longer a hyperparameter, input to model initialization slightly changed). 

If you could make the corresponding edits, that would be great. Additionally, if you could extend the notebook to also train the deckbuilder model, that would be ideal. It's a bit odd that it only trains half the project at the moment.

Sorry about the modifications, but then I should be good to merge it into the scripts folder.

**Comment by RyanSaxe** [comment]
This is out of date now, and training scripts are provided to get started. Closing.

**Pull request closed without merging**
